### PR TITLE
add default for light theme

### PR DESCRIPTION
**Pull request by wvjgsuhp**
I know that we can always add custom highlight groups, but, still, it would be great if light themes are supported out of the box.

image

### CODE REVIEW

**Comment by OXY2DEV** [comment]
The highlight system will be changed to support color scheme specific(light/dark mode too) highlight group.

**Comment by wvjgsuhp** [comment]
whoops  
at least, i didn't go as far to implement a single `fg` for each color and calculate the `bg` from user's `bg` with some opacity setting

**Comment by OXY2DEV** [comment]
> whoops  
> at least, i didn't go as far to implement a single `fg` for each color and calculate the `bg` from user's `bg` with some opacity setting

I actually wanted to implement this. But couldn't really decide whether to add it in the plugin or not.

**Comment by wvjgsuhp** [comment]
i think it's a nice feature for users, so they can try different tones without having to copy and paste too many hex codes  
it also enables auto gradient, and you might not have to check if `bg` is `light` or `dark`

**Comment by wvjgsuhp** [comment]
btw, for this request, you can either merge for light-theme users or close if you see obsolete

**Comment by OXY2DEV** [comment]
> btw, for this request, you can either merge for light-theme users or close if you see obsolete

I was tinkering around the colors and made this.





I think it looks okay.

**Pull request closed without merging**
